//------------------------------------------------------------------------
// Copyright(c) 2023 cma5.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"modeld.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"modeld VST3 (64Bit)"
#else
#define stringFileDescription	"modeld VST3"
#endif
#define stringCompanyName		"cma5\0"
#define stringLegalCopyright	"Copyright(c) 2023 cma5."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
